SELECT
A.CUST_CODE AS CUST_CODE,
LAST_VISIT,
TOTAL_VISIT,
TOTAL_SPEND,
AVG_WEEKLY_VISIT,
AVG_WEEKLY_SPEND,
AVG_BASKET_SIZE,
BASKET_SIZE AS LAST_BASKET_SIZE,
PREVIOUS_1BASKET_SIZE,
PREVIOUS_2BASKET_SIZE
FROM (
SELECT
CUST_CODE AS CUST_CODE,
MAX(SHOP_DATE) AS LAST_VISIT,
MAX(BASKET_ID) AS LAST_BASKET_ID,
COUNT(DISTINCT BASKET_ID) AS TOTAL_VISIT,
SUM(SPEND) AS TOTAL_SPEND,
COUNT(DISTINCT BASKET_ID)/COUNT(DISTINCT SHOP_WEEK) AS AVG_WEEKLY_VISIT,
SUM(SPEND)/COUNT(DISTINCT SHOP_WEEK) AS AVG_WEEKLY_SPEND,
SUM(SPEND)/COUNT(DISTINCT BASKET_ID) AS AVG_BASKET_SIZE,
FROM
`psyched-cab-273503.sp_dataset.sp_table`
WHERE
CUST_CODE IS NOT NULL
GROUP BY
CUST_CODE,
SHOP_WEEK) A
JOIN (
SELECT
CUST_CODE,
BASKET_ID,
BASKET_SIZE,
LAG(BASKET_SIZE, 1) OVER (PARTITION BY CUST_CODE ORDER BY BASKET_ID) AS PREVIOUS_1BASKET_SIZE,
LAG(BASKET_SIZE, 2) OVER (PARTITION BY CUST_CODE ORDER BY BASKET_ID) AS PREVIOUS_2BASKET_SIZE
FROM (
SELECT
CUST_CODE,
BASKET_ID,
SUM(SPEND) AS BASKET_SIZE,
FROM
`psyched-cab-273503.sp_dataset.sp_table`
WHERE
CUST_CODE IS NOT NULL
GROUP BY
CUST_CODE,
BASKET_ID)) B
ON
A.CUST_CODE = B.CUST_CODE
AND A.LAST_BASKET_ID = B.BASKET_ID
